[2023-09-12 05:00:14,433] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: INSERT_TO_PostgreOperator.extract_gz scheduled__2023-09-12T04:00:00+00:00 [queued]>
[2023-09-12 05:00:14,447] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: INSERT_TO_PostgreOperator.extract_gz scheduled__2023-09-12T04:00:00+00:00 [queued]>
[2023-09-12 05:00:14,448] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-09-12 05:00:14,448] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-09-12 05:00:14,448] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-09-12 05:00:14,465] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): extract_gz> on 2023-09-12 04:00:00+00:00
[2023-09-12 05:00:14,470] {standard_task_runner.py:52} INFO - Started process 1499 to run task
[2023-09-12 05:00:14,473] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'INSERT_TO_PostgreOperator', 'extract_gz', 'scheduled__2023-09-12T04:00:00+00:00', '--job-id', '1002', '--raw', '--subdir', 'DAGS_FOLDER/INSERT_TO_PostgreOperator.py', '--cfg-path', '/tmp/tmpilczmrp2', '--error-file', '/tmp/tmpchf53rh0']
[2023-09-12 05:00:14,473] {standard_task_runner.py:80} INFO - Job 1002: Subtask extract_gz
[2023-09-12 05:00:14,544] {task_command.py:371} INFO - Running <TaskInstance: INSERT_TO_PostgreOperator.extract_gz scheduled__2023-09-12T04:00:00+00:00 [running]> on host b18943745c0d
[2023-09-12 05:00:14,637] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=INSERT_TO_PostgreOperator
AIRFLOW_CTX_TASK_ID=extract_gz
AIRFLOW_CTX_EXECUTION_DATE=2023-09-12T04:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-09-12T04:00:00+00:00
[2023-09-12 05:00:14,638] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-09-12 05:00:14,638] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'gunzip --force /tmp/wikipageviews.gz']
[2023-09-12 05:00:14,648] {subprocess.py:85} INFO - Output:
[2023-09-12 05:00:14,708] {subprocess.py:92} INFO - 
[2023-09-12 05:00:14,708] {subprocess.py:92} INFO - gzip: /tmp/wikipageviews.gz: invalid compressed data--format violated
[2023-09-12 05:00:14,710] {subprocess.py:96} INFO - Command exited with return code 1
[2023-09-12 05:00:14,726] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-09-12 05:00:14,731] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=INSERT_TO_PostgreOperator, task_id=extract_gz, execution_date=20230912T040000, start_date=20230912T050014, end_date=20230912T050014
[2023-09-12 05:00:14,748] {standard_task_runner.py:97} ERROR - Failed to execute job 1002 for task extract_gz (Bash command failed. The command returned a non-zero exit code 1.; 1499)
[2023-09-12 05:00:14,766] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-09-12 05:00:14,824] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
